---
kind: pipeline
type: docker
name: test

steps:
- name: test
  image: python:3.9
  commands:
  - pip install --no-cache-dir -r requirements.txt
  - python ./manage.py test --settings=Garage.settings_test

services:
- name: postgres
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: example
    POSTGRES_DB: garage





---
kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: docker
    commands:
      - docker build -t registry.dntsk.dev/garage:latest .
      - docker push registry.dntsk.dev/garage:latest
    volumes:
      - name: cache
        path: /root/.cache/pip
      - name: docker_sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker

volumes:
  - name: cache
    host:
      path: /opt/docker/drone/garage_cache
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: docker_config
    host:
      path: /root/.docker

trigger:
  branch:
    - master
    - staging

depends_on:
  - test
