---
kind: pipeline
type: docker
name: test

steps:
- name: test
  image: python:3.9
  commands:
  - pip install --no-cache-dir -r requirements.txt
  - python ./manage.py test --settings=Garage.settings_test

services:
- name: postgres
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: example
    POSTGRES_DB: garage





---
kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: docker
    commands:
      - docker build -t registry.dntsk.dev/garage:latest .
      - docker push registry.dntsk.dev/garage:latest
    volumes:
      - name: cache
        path: /root/.cache/pip
      - name: docker_sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker

volumes:
  - name: cache
    host:
      path: /garage/docker/drone/cache
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: docker_config
    host:
      path: /root/.docker

trigger:
  branch:
    - master
    - staging

depends_on:
  - test

#---
#kind: pipeline
#type: docker
#name: deploy
#
#steps:
#  - name: deploy_staging
#    image: appleboy/drone-ssh
#    settings:
#      host:
#        from_secret: ssh_host
#      username:
#        from_secret: ssh_username
#      key:
#        from_secret: ssh_key
#      port: 22
#      script:
#        - cd /opt
#        - docker-compose pull garage_staging
#        - docker-compose up -d garage_staging
#    when:
#      branch: staging
