---
kind: pipeline
type: docker
name: test

steps:
- name: test
  image: python:3.9
  commands:
  - pip install --no-cache-dir -r requirements.txt
  - python ./manage.py test

services:
- name: garage
  image: postgres
  ports:
    - 5432
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: example
    POSTGRES_DB: garage
