version: '3.1'

services:

  postgres:
    image: postgres
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: garage
    ports:
      - 5432:5432
