# Generated by Django 3.2 on 2021-04-19 06:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('Garage', '0001_initial'), ('Garage', '0002_auto_20210415_0908'), ('Garage', '0003_auto_20210415_1138'), ('Garage', '0004_auto_20210419_0608')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Тип кузова')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Тип двигателя')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('producer', models.CharField(max_length=300, verbose_name='Марка')),
                ('model', models.CharField(max_length=300, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('transmission', models.CharField(choices=[('ручная/механика', 'Ручная/Механика'), ('автомат', 'Автомат'), ('типтроник', 'Типтроник'), ('робот', 'Робот'), ('вариатор', 'Вариатор')], max_length=20, verbose_name='КПП')),
                ('fuel', models.PositiveIntegerField(choices=[(1, 'Бензин'), (2, 'Дизель'), (3, 'Газ'), (4, 'Газ/Бензин'), (5, 'Гибрид'), (6, 'Электро'), (7, 'Газ метан'), (8, 'Газ пропан-бутан'), (9, 'Другое')], verbose_name='Топливо')),
                ('drive_system', models.PositiveSmallIntegerField(choices=[(1, 'Полный'), (2, 'Передний'), (3, 'Задний')], verbose_name='Тип привода')),
                ('mileage', models.IntegerField(blank=True, null=True, verbose_name='Пробег')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Garage.body')),
                ('engine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Garage.engine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255, verbose_name='Тип страховки')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('policy_number', models.IntegerField(blank=True, verbose_name='Номер страховки')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('price', models.IntegerField(verbose_name='Стоимость страховки')),
                ('car', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Garage.car')),
            ],
        ),
        migrations.CreateModel(
            name='Improvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=255, verbose_name='Название проблемы')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('state', models.BooleanField(default=True, verbose_name='Состояние')),
                ('price', models.IntegerField(blank=True, verbose_name='Стоимость')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garage.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=255, verbose_name='Название проблемы')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('state', models.BooleanField(default=True, verbose_name='Состояние')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garage.car')),
            ],
        ),
    ]
