# Generated by Django 3.2 on 2021-04-19 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0001_squashed_0004_auto_20210419_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carproblem',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='improvement',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='improvement',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garage.car'),
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type_of_repair', models.PositiveSmallIntegerField(choices=[(1, 'ТО'), (2, 'Замена запчастей'), (3, 'Кузовные работы')])),
                ('name', models.CharField(max_length=400, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=2000, verbose_name='Описание')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Примечание')),
                ('mileage', models.IntegerField(blank=True, null=True, verbose_name='Пробег')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
                ('date', models.DateField(blank=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garage.car')),
            ],
        ),
    ]
