# Generated by Django 3.2 on 2021-05-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0004_alter_insurance_policy_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engine',
            options={'verbose_name': 'Тип двигателя', 'verbose_name_plural': 'Типы двигателей'},
        ),
    ]
