# Generated by Django 3.2 on 2021-05-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0005_alter_engine_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='improvement',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='price',
            field=models.FloatField(verbose_name='Стоимость страховки'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость'),
        ),
    ]
