# Generated by Django 3.2 on 2021-05-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0006_auto_20210524_1227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarProblem',
            new_name='CarIssue',
        ),
    ]
