# Generated by Django 3.2 on 2021-07-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0007_rename_carproblem_carissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость страховки'),
        ),
    ]
