# Generated by Django 3.2 on 2021-07-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0008_alter_insurance_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
