# Generated by Django 3.2 on 2021-08-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0009_insurance_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
