# Generated by Django 3.2 on 2021-08-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0010_car_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='carissue',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
