# Generated by Django 3.2 on 2021-08-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0011_carissue_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carissue',
            old_name='state',
            new_name='open',
        ),
    ]
