# Generated by Django 3.2 on 2021-09-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0016_alter_carissue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carissue',
            name='open',
        ),
        migrations.AddField(
            model_name='carissue',
            name='close',
            field=models.BooleanField(default=False, verbose_name='Состояние'),
        ),
    ]
