# Generated by Django 3.2 on 2021-09-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0018_improvement_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='improvement',
            name='state',
        ),
        migrations.AddField(
            model_name='improvement',
            name='close',
            field=models.BooleanField(default=False, verbose_name='Состояние'),
        ),
    ]
