# Generated by Django 3.2 on 2021-11-30 08:24

import Garage.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0023_carphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carphoto',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Garage.car'),
        ),
        migrations.AlterField(
            model_name='carphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Garage.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='carphoto',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
