# Generated by Django 3.2 on 2021-12-07 09:11

import Garage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0025_auto_20211130_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Garage.models.user_directory_path, verbose_name='Фото'),
        ),
    ]
