# Generated by Django 3.2 on 2022-02-14 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0027_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvement',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000000.0)], verbose_name='Стоимость'),
        ),
    ]
