# Generated by Django 3.2 on 2022-04-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0038_alter_car_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[(1, 'Ручная/Механика'), (2, 'Автомат'), (3, 'Типтроник'), (4, 'Робот'), (5, 'Вариатор')], max_length=20, verbose_name='КПП'),
        ),
    ]
